name: Versioning.NET - Auto Version

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ]

jobs:
  increment-version:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUBACCESSTOKEN }}

    - name: Import GPG & Enable Git Signing
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-import-gpg@111c56156bcc6918c056dbef52164cfa583dc549
      uses: crazy-max/ghaction-import-gpg@v5.2.0
      with:
        gpg_private_key: ${{ secrets.COMMIT_SIGNINGKEY }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true
        git_push_gpgsign: true
  
    - name: Reset Origin
      run: |
        git remote set-url origin "https://cbcrouse:${{ secrets.GITHUBACCESSTOKEN }}@github.com/cbcrouse/Versioning.NET.git"
        git checkout ${{ github.ref_name }}

    - name: Install Versioning.NET
      run: |
        dotnet tool install --global Versioning.NET

    - name: Increment Version
      run: |
        dotnet-version increment-version-with-git-hints -g "." --branch-name ${{ github.ref_name }} --author-email ${{ secrets.COMMIT_SIGNING_EMAIL }}
